import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Stack } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BeforeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Stack
      bgcolor={"pink"}
      flex={1}
      direction={"row"}
      justifyContent={"space-between"}
      height={"100vh"}
    >
      <Stack sx={{ flex: 1, bgcolor: "yellow" }}>left</Stack>
      <Stack
        sx={{
          width: "500px",
          bgcolor: "blue",
          flexDirection: "row",
          justifyContent: "center",
          paddingTop: "100px",
        }}
      >
        {children}
      </Stack>
    </Stack>
  );
}
